
import { Category, MenuItem } from './types';

export const MOCK_MENU_ITEMS: MenuItem[] = [
  // Original Meals
  {
    id: '1',
    name: 'Indian Fried Chicken Rice',
    category: Category.MEALS,
    description: 'Rice, Fried Chicken, Special Spices, Herbs',
    calories: { fat: 26, saturatedFat: 18, transFat: 0.7 },
    price: 349,
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?q=80&w=800&auto=format&fit=crop',
    prepTime: 15,
    quote: "Crispy perfection meets aromatic spices.",
    available: true,
  },
  {
    id: '3',
    name: 'Vegetable Garlic Bread',
    category: Category.MEALS,
    description: 'Garlic, All Purpose Flour, Vegetables, Spl Spices',
    calories: { fat: 16, saturatedFat: 7, transFat: 0.4 },
    price: 199,
    image: 'https://www.vegrecipesofindia.com/wp-content/uploads/2015/07/cheese-garlic-bread-recipe-1-500x375.jpg',
    prepTime: 10,
    quote: "Golden, buttery, and irresistibly cheesy.",
    available: true,
  },
  {
    id: '4',
    name: 'Chinese Tofu Spaghetti',
    category: Category.MEALS,
    description: 'Noodles, Tofu, Veg Oil, Vegetables, Spl Spices',
    calories: { fat: 16, saturatedFat: 11, transFat: 0.6 },
    price: 299,
    image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?q=80&w=800&auto=format&fit=crop',
    prepTime: 20,
    quote: "A delightful fusion of textures and tastes.",
    available: true,
  },
  
  // New Indian Items
  {
    id: '8',
    name: 'Butter Chicken (with Garlic Naan)',
    category: Category.MEALS,
    description: 'Tender chicken in creamy tomato sauce, fenugreek, butter',
    calories: { fat: 35, saturatedFat: 15, transFat: 0.5 },
    price: 449,
    image: 'https://images.services.kitchenstories.io/DnuV2UQLbLsafICFmiMEUCMXXOg=/3840x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/SV0207-photo-final-2.jpg',
    prepTime: 20,
    isPopular: true,
    quote: "Creamy tomato bliss with a buttery finish.",
    available: true,
  },
  {
    id: '9',
    name: 'Hyderabadi Dum Biryani',
    category: Category.MEALS,
    description: 'Aromatic basmati rice, tender chicken or mutton, saffron, mint',
    calories: { fat: 28, saturatedFat: 8, transFat: 0 },
    price: 399,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
    prepTime: 25,
    quote: "A royal symphony of saffron and spice.",
    available: true,
  },
  {
    id: '10',
    name: 'Dal Makhani (with Laccha Paratha)',
    category: Category.MEALS,
    description: 'Black lentils simmered overnight, cream, butter, mild spices',
    calories: { fat: 25, saturatedFat: 12, transFat: 0.2 },
    price: 349,
    image: 'https://i.redd.it/yg5wwww3de111.jpg',
    prepTime: 15,
    quote: "Slow-cooked velvety goodness.",
    available: true,
  },
  {
    id: '11',
    name: 'Paneer Tikka Masala (with Naan)',
    category: Category.MEALS,
    description: 'Grilled cottage cheese cubes, spicy gravy, bell peppers, onions',
    calories: { fat: 30, saturatedFat: 14, transFat: 0 },
    price: 379,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop',
    prepTime: 18,
    quote: "Char-grilled cubes in a rich spiced gravy.",
    available: true,
  },
  {
    id: '12',
    name: 'Chole Bhature (with Onions)',
    category: Category.MEALS,
    description: 'Spicy chickpea curry, fluffy deep-fried bread, onions, tangy pickle',
    calories: { fat: 40, saturatedFat: 10, transFat: 1.5 },
    price: 249,
    image: 'https://madhurasrecipe.com/wp-content/uploads/2025/09/MR-Chole-Bhature-featured.jpg',
    prepTime: 15,
    quote: "The ultimate North Indian comfort food.",
    available: true,
  },
  {
    id: '15',
    name: 'Palak Paneer (with Missi Roti)',
    category: Category.MEALS,
    description: 'Cottage cheese cubes, spinach puree, garlic, cream, spices',
    calories: { fat: 22, saturatedFat: 10, transFat: 0 },
    price: 329,
    image: 'https://images.unsplash.com/photo-1589647363585-f4a7d3877b10?q=80&w=800&auto=format&fit=crop',
    prepTime: 15,
    quote: "Fresh greens meet creamy cottage cheese.",
    available: true,
  },
  {
    id: '17',
    name: 'Kashmiri Dum Aloo (with Jeera Rice)',
    category: Category.MEALS,
    description: 'Baby potatoes, yogurt-based gravy, fennel, dry ginger, spices',
    calories: { fat: 15, saturatedFat: 5, transFat: 0 },
    price: 299,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAw28iqcWISfjoqWTK3p7qTtFeqzf2DNbhkA&s',
    prepTime: 18,
    quote: "Potatoes simmered in Kashmiri traditions.",
    available: true,
  },

  // Drinks
  {
    id: '5',
    name: 'Tropical Fruit Punch',
    category: Category.DRINKS,
    description: 'Orange, Pineapple, Grenadine, Ice',
    calories: { fat: 0, saturatedFat: 0, transFat: 0 },
    price: 149,
    image: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?q=80&w=800&auto=format&fit=crop',
    prepTime: 5,
    quote: "A tropical vacation in a glass.",
    available: true,
  },
  {
    id: '6',
    name: 'Mango Lassi',
    category: Category.DRINKS,
    description: 'Yogurt, Mango Pulp, Sugar, Cardamom',
    calories: { fat: 5, saturatedFat: 3, transFat: 0 },
    price: 129,
    image: 'https://www.yellowthyme.com/wp-content/uploads/2023/03/Mango-Lassi-08589-819x1024.jpg',
    prepTime: 5,
    quote: "The golden nectar of summer.",
    available: true,
  },
  {
    id: '18',
    name: 'Classic Cold Coffee',
    category: Category.DRINKS,
    description: 'Chilled milk, espresso, sugar, ice cream topping',
    calories: { fat: 12, saturatedFat: 8, transFat: 0 },
    price: 189,
    image: 'https://bakewithshivesh.com/wp-content/uploads/2021/04/IMG_3613-scaled.jpg',
    prepTime: 8,
    quote: "Chilled caffeine for the soul.",
    available: true,
  },
  {
    id: '19',
    name: 'Virgin Mojito',
    category: Category.DRINKS,
    description: 'Fresh mint, lime, sugar, soda water, ice',
    calories: { fat: 0, saturatedFat: 0, transFat: 0 },
    price: 159,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=800&auto=format&fit=crop',
    prepTime: 5,
    quote: "Zesty, minty, and refreshing.",
    available: true,
  },
  {
    id: '20',
    name: 'Blue Lagoon',
    category: Category.DRINKS,
    description: 'Blue curaçao syrup, lemon juice, soda, ice',
    calories: { fat: 0, saturatedFat: 0, transFat: 0 },
    price: 169,
    image: 'https://monin.in/cdn/shop/products/Blue_20Lagoon.png?v=1681306671&width=1100',
    prepTime: 5,
    quote: "A cool splash of citrusy blue.",
    available: true,
  },
  {
    id: '21',
    name: 'Masala Chai',
    category: Category.DRINKS,
    description: 'Brewed black tea, milk, aromatic indian spices',
    calories: { fat: 4, saturatedFat: 2, transFat: 0 },
    price: 89,
    image: 'https://www.thespicehouse.com/cdn/shop/articles/Chai_Masala_Tea_720x.jpg?v=1606936195',
    prepTime: 10,
    quote: "Warm spices brewed to perfection.",
    available: true,
  },
  {
    id: '22',
    name: 'Oreo Milkshake',
    category: Category.DRINKS,
    description: 'Milk, vanilla ice cream, oreo cookies, chocolate syrup',
    calories: { fat: 18, saturatedFat: 10, transFat: 0.5 },
    price: 219,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=800&auto=format&fit=crop',
    prepTime: 10,
    quote: "Creamy, crunchy cookie delight.",
    available: true,
  },
  {
    id: '23',
    name: 'Watermelon Cooler',
    category: Category.DRINKS,
    description: 'Fresh watermelon juice, mint, lemon, ice',
    calories: { fat: 0, saturatedFat: 0, transFat: 0 },
    price: 139,
    image: 'https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?q=80&w=800&auto=format&fit=crop',
    prepTime: 6,
    quote: "Freshly pressed summer hydration.",
    available: true,
  },

  // Desserts
  {
    id: '7',
    name: 'Chocolate Lava Cake',
    category: Category.DESSERTS,
    description: 'Dark Chocolate, Butter, Flour, Eggs, Sugar',
    calories: { fat: 22, saturatedFat: 12, transFat: 0.5 },
    price: 249,
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?q=80&w=800&auto=format&fit=crop',
    prepTime: 15,
    quote: "A molten chocolate explosion.",
    available: true,
  },
  {
    id: '24',
    name: 'Gulab Jamun (with Rabri)',
    category: Category.DESSERTS,
    description: 'Soft milk solids dumplings soaked in rose sugar syrup, served with creamy rabri',
    calories: { fat: 18, saturatedFat: 10, transFat: 0 },
    price: 199,
    image: 'https://i.pinimg.com/736x/d1/77/de/d177de8582f96a8ec9cd947b183daf68.jpg',
    prepTime: 10,
    quote: "Sweet golden orbs of joy.",
    available: true,
  },
  {
    id: '25',
    name: 'Classic Rasmalai',
    category: Category.DESSERTS,
    description: 'Soft paneer balls soaked in chilled, thickened milk with saffron and pistachios',
    calories: { fat: 14, saturatedFat: 8, transFat: 0 },
    price: 219,
    image: 'https://static.wixstatic.com/media/bb82ca_4d9c677edfc644bc8ed0503c436b8adf~mv2.png/v1/fill/w_740,h_494,al_c,q_90,usm_0.66_1.00_0.01,enc_avif,quality_auto/bb82ca_4d9c677edfc644bc8ed0503c436b8adf~mv2.png',
    prepTime: 5,
    quote: "Saffron-infused milky indulgence.",
    available: true,
  },
  {
    id: '26',
    name: 'Sizzling Brownie',
    category: Category.DESSERTS,
    description: 'Walnut brownie served on a hot sizzler plate with vanilla ice cream and chocolate sauce',
    calories: { fat: 28, saturatedFat: 15, transFat: 0.8 },
    price: 299,
    image: 'https://instamart-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_960,w_960//InstamartAssets/2/sizzler_brownie.webp?updatedAt=1730797768004',
    prepTime: 15,
    quote: "Hot meets cold on a sizzler.",
    available: true,
  },
  {
    id: '27',
    name: 'Classic Tiramisu',
    category: Category.DESSERTS,
    description: 'Coffee-flavoured Italian dessert with mascarpone cheese and cocoa',
    calories: { fat: 24, saturatedFat: 14, transFat: 0.5 },
    price: 349,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?q=80&w=800&auto=format&fit=crop',
    prepTime: 10,
    quote: "Layers of coffee-soaked elegance.",
    available: true,
  },
  {
    id: '28',
    name: 'New York Cheesecake',
    category: Category.DESSERTS,
    description: 'Rich and creamy cheesecake with a graham cracker crust and berry compote',
    calories: { fat: 32, saturatedFat: 18, transFat: 1.0 },
    price: 399,
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?q=80&w=800&auto=format&fit=crop',
    prepTime: 12,
    quote: "Rich, creamy, and berry-topped.",
    available: true,
  },
  {
    id: '29',
    name: 'Tropical Fruit Sundae',
    category: Category.DESSERTS,
    description: 'Fresh seasonal fruits served with vanilla bean ice cream and honey',
    calories: { fat: 10, saturatedFat: 6, transFat: 0 },
    price: 229,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop',
    prepTime: 8,
    quote: "Nature's freshness in every scoop.",
    available: true,
  },
];
